### ISSUE TITLE
Can not Authorize

### ISSUE THREAD

**Issue by EffortlessFury** [dim-stream-deck/com.dim.streamdeck#1]
It would seem that DIM is hardcoded to use port 9119 for the plugin, whereas the documentation and the codebase here suggest that the StreamDeck application are dictating the port. How does Authorization work now?

**Comment by EffortlessFury** [comment]
Ah, nevermind. Found the port (9120). I suppose we have to wait for a DIM update then?

**Comment by fcannizzaro** [comment]
I'm delaying the DIM update until the store plugin is updated. (Follow the status on discord)
