### ISSUE TITLE
Picker feature - weapon filter bug

### ISSUE THREAD

**Issue by seapsychodonniedarko** [dim-stream-deck/com.dim.streamdeck#17]
When using the Picker feature, and then trying to filter by weapon type, the bottom left button lists a weapon type (Fusion Rifle) but pressing it exits out, without filtering. It seems it functions as the exit/close button, but renders as one of the weapon types.

**Comment by fcannizzaro** [comment]
Which Stream Deck model? Maybe I messed up something for models I have not (XL, mini ?)
