### ISSUE TITLE
Plugin not working and cannot be uninstalled

### ISSUE THREAD

**Issue by zstoichev** [dim-stream-deck/com.dim.streamdeck#4]
Looking at Deck logs:
20:33:02.212                     StreamDeck                        ESDCustomPlugin::onNativeProcessFinished():     The plugin 'DIM Stream Deck' crashed with code -1073740791
20:33:02.212                     StreamDeck                        ESDCustomPlugin::restartNativeProcess():        Restarting plugin 'DIM Stream Deck' in 60 seconds(s)

**Comment by fcannizzaro** [comment]
can you check the latest release [2.0.3](https://github.com/dim-stream-deck/com.dim.streamdeck/releases/tag/2.0.3) ?

**Comment by zstoichev** [comment]
the new ver is not avail on Stream Store yet, After manual install from here, it resolved the issue. Thank you!

**Comment by zstoichev** [comment]
postmaster and vault counters do not show thou
